### ISSUE TITLE
Issue while running classifier

### ISSUE THREAD

**Issue by GavinDmello** [tuwien-musicir/rp_extract#22]
```
Traceback (most recent call last):
  File "rp_classify.py", line 322, in <module>
    predictions = classify(model, features_to_classify, labelencoder)
  File "rp_classify.py", line 62, in classify
    pred = model.predict(features)
  File "/Library/Python/2.7/site-packages/sklearn/multiclass.py", line 305, in predict
    return self.classes_[np.array(argmaxima.T)]
AttributeError: 'OneVsRestClassifier' object has no attribute 'classes_'
```

**Comment by audiofeature** [comment]
What version of scikit-learn are you using?

**Comment by GavinDmello** [comment]
0.18.1

**Comment by audiofeature** [comment]
as per requirements.txt rp_extract was written for scikit-learn==0.17

Please feel free to research on scikit-learn docs how the classes are retrieved in 0.18 and suggest it here or as a pull request

**Comment by GavinDmello** [comment]
@audiofeature  Thanks dude.
